# Generated by Django 6.0.3 on 2026-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_user_movie_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(default='G', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='english', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
