# Generated by Django 6.0.3 on 2026-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(related_name='tickets', to='core.seat'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
