# Generated by Django 6.0.3 on 2026-05-13 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_ticket_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cols',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='rows',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='screening',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SPECTATOR', 'Spectator')], default='SPECTATOR', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
