# Generated by Django 6.0.3 on 2026-05-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_room_cols_room_rows_screening_price_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
