# Generated by Django 6.0.3 on 2026-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
