# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_membership_type_profile_monthly_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='price',
            new_name='base_price',
        ),
    ]
